force-app/main/default/objects/BatchGroup__c/BatchGroup__c.object-meta.xml
<CustomObject>
    <label>Batch Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchGroup__c/fields/CronText__c.field-meta.xml
<CustomField>
    <fullName>CronText__c</fullName>
    <description>스케줄 실행 시간</description>
    <label>Cron Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <label>Group Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchManager__c/BatchManager__c.object-meta.xml
<CustomObject>
    <label>Batch Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchManager__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>활성 여부</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchManager__c/fields/ScopeSize__c.field-meta.xml
<CustomField>
    <fullName>ScopeSize__c</fullName>
    <label>Scope Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchSequenceManager__c/BatchSequenceManager__c.object-meta.xml
<CustomObject>
    <label>Batch Sequence Manager</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchGroup__c.field-meta.xml
<CustomField>
    <fullName>BatchGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Group</label>
    <referenceTo>BatchGroup__c</referenceTo>
    <relationshipLabel>Batch Manager</relationshipLabel>
    <relationshipName>BatchManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchManager__c.field-meta.xml
<CustomField>
    <fullName>BatchManager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BatchManager</label>
    <referenceTo>BatchManager__c</referenceTo>
    <relationshipName>BatchSequanceManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MasterQueueable_Test.cls
@isTest
public class MasterQueueable_Test {
    @TestSetup
    static void makeData(){
        BatchManager__c batchManager = new BatchManager__c(
            Name = 'TestBatch'
            , Active__c = true
            , ScopeSize__c = 200
            , Params__c = 'test'
        );

        Insert batchManager;

        BatchManager__c batchManager2 = new BatchManager__c(
            Name = 'TestBatch2'
            , Active__c = true
            , ScopeSize__c = 200
            , Params__c = 'test'
        );

        Insert batchManager2;

        BatchManager__c batchManager3 = new BatchManager__c(
            Name = 'TestQueueable'
            , Active__c = true
            , Params__c = 'TEST'
        );

        Insert batchManager3;

        BatchGroup__c batchGroup = new BatchGroup__c(
            Name = 'Test Group'
            , Schedule__c = false
            , GroupName__c = 'Test Group'
        );

        Insert batchGroup;

        BatchGroup__c batchGroup2 = new BatchGroup__c(
            Name = 'Test Group2'
            , Schedule__c = true
            , GroupName__c = 'Test Group2'
            , Interval__c = 5
        );

        Insert batchGroup2;

        BatchGroup__c batchGroup3 = new BatchGroup__c(
            Name = 'Test Group3'
            , Schedule__c = true
            , GroupName__c = 'Test Group3'
            , cronText__c = '0 0 5 * * ?'
        );

        Insert batchGroup3;

        BatchSequenceManager__c sequenceManager = new BatchSequenceManager__c(
            Name = 'TestBatch'
            , Sequence__c = 1
            , BatchManager__c = batchManager.Id
            , BatchGroup__c = batchGroup.Id
        );

        Insert sequenceManager;

        BatchSequenceManager__c sequenceManager2 = new BatchSequenceManager__c(
            Name = 'TestBatch2'
            , Sequence__c = 2
            , BatchManager__c = batchManager2.Id
            , BatchGroup__c = batchGroup.Id
        );

        Insert sequenceManager2;

        BatchSequenceManager__c sequenceManager3 = new BatchSequenceManager__c(
            Name = 'TestBatch2'
            , Sequence__c = 1
            , BatchManager__c = batchManager2.Id
            , BatchGroup__c = batchGroup2.Id
        );

        Insert sequenceManager3;

        BatchSequenceManager__c sequenceManager4 = new BatchSequenceManager__c(
            Name = 'TestQueueable'
            , Sequence__c = 1
            , BatchManager__c = batchManager3.Id
            , BatchGroup__c = batchGroup3.Id
        );

        Insert sequenceManager4;

        BatchSequenceManager__c sequenceManager5 = new BatchSequenceManager__c(
            Name = 'TestBatch'
            , Sequence__c = 2
            , BatchManager__c = batchManager.Id
            , BatchGroup__c = batchGroup3.Id
        );

        Insert sequenceManager5;
    }

    @isTest
    static void test1(){
        Test.StartTest();
        TestQueueable batch = new TestQueueable();
        System.enqueueJob(batch);
        Test.StopTest();
    }

    @isTest
    static void test2(){
        Test.StartTest();
        new BatchManager('TestQueueable', true).execute();
        Test.StopTest();
    }

    @isTest
    static void test3(){
        List<BatchSequenceManager__c> sequenceList = [SELECT Id, Sequence__c FROM BatchSequenceManager__c WHERE BatchGroup__r.Name = 'Test Group3' ORDER BY Sequence__c];
        
        sequenceList[0].Sequence__c = 2;
        sequenceList[1].Sequence__c = 1;

        Update sequenceList;

        Test.StartTest();
        new BatchManager('TestQueueable', true).execute();
        Test.StopTest();
    }

    @isTest
    static void test4(){
        Test.StartTest();
        new BatchManager('TestQueueable', false).execute();
        Test.StopTest();
    }

    @isTest
    static void test5(){
        Test.StartTest();
        TestQueueable batch = new TestQueueable();
        batch.isTest = true;
        System.enqueueJob(batch);
        Test.StopTest();
    }

}