force-app/main/default/objects/BatchGroup__c/BatchGroup__c.object-meta.xml
<CustomObject>
    <label>Batch Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchGroup__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <label>Group Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchManager__c/BatchManager__c.object-meta.xml
<CustomObject>
    <label>Batch Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchManager__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>활성 여부</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchManager__c/fields/ScopeSize__c.field-meta.xml
<CustomField>
    <fullName>ScopeSize__c</fullName>
    <label>Scope Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchSequenceManager__c/BatchSequenceManager__c.object-meta.xml
<CustomObject>
    <label>Batch Sequence Manager</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchGroup__c.field-meta.xml
<CustomField>
    <fullName>BatchGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Group</label>
    <referenceTo>BatchGroup__c</referenceTo>
    <relationshipLabel>Batch Manager</relationshipLabel>
    <relationshipName>BatchManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchManager__c.field-meta.xml
<CustomField>
    <fullName>BatchManager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BatchManager</label>
    <referenceTo>BatchManager__c</referenceTo>
    <relationshipName>BatchSequanceManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MasterBatch_Test.cls
@isTest
public class MasterBatch_Test {
    @TestSetup
    static void setup(){
        Account account = new Account(
            Name = 'TEST'
        );

        Insert account;

        BatchManager__c batchManager = new BatchManager__c(
            Name = 'TestBatch'
            , Active__c = true
            , ScopeSize__c = 200
            , Params__c = 'test'
        );

        Insert batchManager;

        BatchManager__c batchManager2 = new BatchManager__c(
            Name = 'TestBatch2'
            , Active__c = true
            , ScopeSize__c = 200
            , Params__c = 'test'
        );

        Insert batchManager2;

        BatchGroup__c batchGroup = new BatchGroup__c(
            Name = 'Test Group'
            , Schedule__c = false
            , GroupName__c = 'Test Group'
        );

        Insert batchGroup;

        BatchSequenceManager__c sequenceManager = new BatchSequenceManager__c(
            Name = 'TestBatch'
            , Sequence__c = 1
            , BatchManager__c = batchManager.Id
            , BatchGroup__c = batchGroup.Id
        );

        Insert sequenceManager;

        BatchSequenceManager__c sequenceManager2 = new BatchSequenceManager__c(
            Name = 'TestBatch2'
            , Sequence__c = 2
            , BatchManager__c = batchManager2.Id
            , BatchGroup__c = batchGroup.Id
        );

        Insert sequenceManager2;
    }

    @isTest
    static void test1(){
        Test.StartTest();
        new BatchManager('TestBatch', true).execute();
        Test.StopTest();
    }

    @isTest
    static void test2(){
        Test.StartTest();
        TestBatch batch = new TestBatch();
        Database.executeBatch(batch);
        Test.StopTest();
    }

    @isTest
    static void test3(){
        Test.StartTest();
        Account account = [SELECT Id, Name FROM Account WHERE Name = 'TEST'];
        account.Name = 'exception';

        Update account;

        TestBatch batch = new TestBatch();
        Database.executeBatch(batch);
        Test.StopTest();
    }
/*
    @isTest
    static void test4(){
        Test.StartTest();
        TestBatch2 batch = new TestBatch2();
        batch.queryStatement = 'Exception Query';
        Database.executeBatch(batch);
        Test.StopTest();
    }*/

    @isTest
    static void test5(){
        Test.StartTest();
        List<BatchSequenceManager__c> sequenceList = [SELECT Id FROM BatchSequenceManager__c];
        Delete sequenceList;
        TestBatch batch = new TestBatch();

        IF_Order__c ifObj = new IF_Order__c(
            IFExternalKey__c = 'test'
        );
        List<IF_Order__c> ifObjList = new List<IF_Order__c>();
        ifObjList.add(ifObj);

        Database.UpsertResult[] urList = Database.Upsert(ifObjList, IF_Order__c.IFExternalKey__c, false);
        Database.SaveResult[] srList = Database.Update(ifObjList, false);

        batch.scheduleExecute();
        batch.saveDMLLog(urList);
        batch.saveDMLLog(srList);

        Database.executeBatch(batch);
        Test.StopTest();
    }
    
    class TestBatch extends MasterBatch{
        public override String startFunction(){
            this.queryStatement = 'SELECT Id'
                + ' FROM Account'
                + ' WHERE Name = \'TEST\''
                + ' ORDER BY LastModifiedDate DESC'
                + ' LIMIT 1';

            return this.queryStatement;
        }

        public override void executeFunction(sObject[] scope){
            List<Account> accountList = (List<Account>)scope;

            System.assertEquals(accountList[0].Name, 'TEST');
        }
    }

    class TestBatch2 extends MasterBatch{
        public override String startFunction(){
            this.queryStatement = 'Exception Query';

            return this.queryStatement;
        }

        public override void executeFunction(sObject[] scope){
            
        }
    }
    
}