force-app/main/default/objects/BatchGroup__c/BatchGroup__c.object-meta.xml
<CustomObject>
    <label>Batch Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchGroup__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <label>Group Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchGroup__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BatchManager__c/BatchManager__c.object-meta.xml
<CustomObject>
    <label>Batch Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchSequenceManager__c/BatchSequenceManager__c.object-meta.xml
<CustomObject>
    <label>Batch Sequence Manager</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchGroup__c.field-meta.xml
<CustomField>
    <fullName>BatchGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Group</label>
    <referenceTo>BatchGroup__c</referenceTo>
    <relationshipLabel>Batch Manager</relationshipLabel>
    <relationshipName>BatchManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatchSequenceManager__c/fields/BatchManager__c.field-meta.xml
<CustomField>
    <fullName>BatchManager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BatchManager</label>
    <referenceTo>BatchManager__c</referenceTo>
    <relationshipName>BatchSequanceManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchGroupManagementController_Test.cls
/**
 * 
 * @author 조형준
 * @since 2022. 12. 30
 * @description BatchGroupManagementController Test Class
 * @group Trigger
 * 
 */
@isTest
public with sharing class BatchGroupManagementController_Test {
    @TestSetup
    static void makeData(){
        IF_TestDataFactory fac = new IF_TestDataFactory();
        // fac.createAlertManager();
        fac.createBatchManager();

        BatchGroup__c bg = new BatchGroup__c(
            Name = 'Test Group'
            ,GroupName__c = 'Test Group'
            ,Schedule__c = true
            ,Interval__c = 5
        );
        Insert bg;

        List<BatchManager__c> bmList = [SELECT Id
                                                ,Name
                                        FROM BatchManager__c
                                        WHERE Name LIKE '%Test%'
                                        ];
        
        BatchSequenceManager__c bsm = new BatchSequenceManager__c(
            BatchGroup__c = bg.Id
            ,BatchManager__c = bmList[0].Id
            ,Sequence__c = 1
        );
        Insert bsm;
    }

    @isTest
    static void test1(){
        Test.StartTest();
        BatchGroupManagementController.getGroupData();
        BatchGroupManagementController.getSequenceData();
        BatchGroupManagementController.getTableData();
        BatchGroupManagementController.scheduledBatch('Test Group');
        BatchGroupManagementController.abortSchedule('Test Group');
        BatchGroupManagementController.executeBatch('TestBatch');
        BatchGroupManagementController.getScheduleData();
        Test.StopTest();
    }
}