force-app/main/default/objects/API_Routing__mdt/API_Routing__mdt.object-meta.xml
<CustomObject>
    <description>API Route 관리 메타데이터</description>
    <label>API Routing</label>
</CustomObject>

force-app/main/default/objects/API_Routing__mdt/fields/ExampleParam__c.field-meta.xml
<CustomField>
    <fullName>ExampleParam__c</fullName>
    <label>ExampleParam</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/InterfaceID__c.field-meta.xml
<CustomField>
    <fullName>InterfaceID__c</fullName>
    <label>InterfaceID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/ServiceClass__c.field-meta.xml
<CustomField>
    <fullName>ServiceClass__c</fullName>
    <label>ServiceClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/timeout__c.field-meta.xml
<CustomField>
    <fullName>timeout__c</fullName>
    <label>timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/API_Service_Test.cls
/**
 * @description       : 
 * @author            : hj.jo@dkbmc.com
 * @group             : 
 * @last modified on  : 05-31-2023
 * @last modified by  : hj.jo@dkbmc.com
**/
@IsTest
public class API_Service_Test {
    private static FINAL API_Routing__mdt apiRouting = getTestApiRoutingRecord();
    public static FINAL API_Request apiRequest = new API_Request(apiRouting.serviceClass__c, apiRouting.ExampleParam__c);

    @TestSetup
    static void makeData(){
    }

    @IsTest
    public static API_Routing__mdt getTestApiRoutingRecord(){
        API_Routing__mdt result = [SELECT Id
                                        , InterfaceId__c 
                                        , ServiceClass__c
                                        , ExampleParam__c
                                        , isActive__c
                                        , timeout__c
                                    FROM API_Routing__mdt
                                    ORDER BY InterfaceId__c
                                    LIMIT 1
                                    ];

        return result;
    }
    
    @IsTest
    public static void testHandleRequest() {
        Test.startTest();
        API_Sender apiSender = new API_Sender();
        HttpResponse response = apiSender.handleRequest(apiRequest);
        Test.stopTest();
    }
}