force-app/main/default/objects/API_Routing__mdt/API_Routing__mdt.object-meta.xml
<CustomObject>
    <description>API Route 관리 메타데이터</description>
    <label>API Routing</label>
</CustomObject>

force-app/main/default/objects/API_Routing__mdt/fields/ExampleParam__c.field-meta.xml
<CustomField>
    <fullName>ExampleParam__c</fullName>
    <label>ExampleParam</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <label>Http Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/InterfaceID__c.field-meta.xml
<CustomField>
    <fullName>InterfaceID__c</fullName>
    <label>InterfaceID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/LegacySystem__c.field-meta.xml
<CustomField>
    <fullName>LegacySystem__c</fullName>
    <label>LegacySystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/ServiceClass__c.field-meta.xml
<CustomField>
    <fullName>ServiceClass__c</fullName>
    <label>ServiceClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Routing__mdt/fields/URI__c.field-meta.xml
<CustomField>
    <fullName>URI__c</fullName>
    <label>URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LegacySystem__c/LegacySystem__c.object-meta.xml
<CustomObject>
    <label>Legacy System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/API_ManagementController.cls
/**
 * @description       : 
 * @author            : hj.jo@dkbmc.com
 * @group             : 
 * @last modified on  : 04-13-2023
 * @last modified by  : hj.jo@dkbmc.com
**/
public with sharing class API_ManagementController {
    @AuraEnabled(cacheable=false)
    public static List<API_Routing__mdt> getAPIData(){
        List<API_Routing__mdt> apiList = [SELECT Id
                                                , Label
                                                , URI__c
                                                , HttpMethod__c
                                                , InterfaceID__c
                                                , isActive__c
                                                , Description__c
                                                , ExampleParam__c
                                                , ServiceClass__c
                                                , LegacySystem__c 
                                            FROM API_Routing__mdt
                                            ];
        return apiList;
    }
}