force-app/main/default/objects/InterfaceRouteManager__c/InterfaceRouteManager__c.object-meta.xml
<CustomObject>
    <label>I/F Route Manager</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceRouteManager__c/fields/ExampleParam__c.field-meta.xml
<CustomField>
    <fullName>ExampleParam__c</fullName>
    <label>Example Param</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InterfaceRouteManager__c/fields/InterfaceId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceId__c</fullName>
    <label>Interface ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InterfaceRouteManager__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Service Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InterfaceRouteManager__c/fields/TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>TargetSystem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target System</label>
    <referenceTo>LegacySystem__c</referenceTo>
    <relationshipLabel>I/F Route Manager</relationshipLabel>
    <relationshipName>InterfaceRouteManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LegacySystem__c/LegacySystem__c.object-meta.xml
<CustomObject>
    <label>Legacy System</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/InterfaceRouteManagementController.cls
/**
 * 
 * @author 조형준
 * @since 22. 08. 30
 */
public without sharing class InterfaceRouteManagementController {
    @AuraEnabled(cacheable=true)
    public static resultInitWrapper getInitData(){
        resultInitWrapper result = new resultInitWrapper();
        try {
            List<LegacySystem__c> legacySystemList = [SELECT Id
                                                            , Name 
                                                        FROM LegacySystem__c
                                                        ORDER BY Name ASC];

            List<InterfaceRouteManager__c> interfaceRouteList = [SELECT Id
                                                                        , TargetSystem__c
                                                                        , ServiceName__c 
                                                                        , InterfaceId__c
                                                                        , ExampleParam__c 
                                                                    FROM InterfaceRouteManager__c
                                                                    ORDER BY TargetSystem__c ASC, ServiceName__c ASC];
            
            Map<String, List<interfaceOptions>> interfaceRouteMap = new Map<String, List<interfaceOptions>>();
            Map<String, String> exampleParamMap = new Map<String, String>();
            for(InterfaceRouteManager__c obj : interfaceRouteList){
                List<interfaceOptions> tempList = new List<interfaceOptions>();

                if(interfaceRouteMap.get(obj.TargetSystem__c) != null) tempList = interfaceRouteMap.get(obj.TargetSystem__c);
                tempList.add(new interfaceOptions(obj));

                interfaceRouteMap.put(obj.TargetSystem__c, tempList);
                exampleParamMap.put(obj.ServiceName__c, obj.ExampleParam__c);
            }

            result.legacySystemList = legacySystemList;
            result.interfaceRouteMap = interfaceRouteMap;
            result.exampleParamMap = exampleParamMap;

            //앱 정보 확인 테스트 추가
            UserAppInfo userAppInfo = [SELECT Id, AppDefinitionId FROM UserAppInfo WHERE UserId = :UserInfo.getUserId() LIMIT 1];
            AppDefinition appDefinition = [SELECT DeveloperName FROM AppDefinition WHERE DurableId = :userAppInfo.AppDefinitionId LIMIT 1];
            result.appName = appDefinition.DeveloperName;

            System.debug('result : ' + result);
        } catch (Exception e) {
            Logger.error(e.getStackTraceString());
            Logger.error(e.getMessage());
            Logger.saveLog();
        }
        return result;
    }

    @AuraEnabled(cacheable=false)
    public static string callout(String serviceName, Object params){
        String result;
        try {
            ApiCommonRequest apiRequest = new ApiCommonRequest(serviceName, params);
            System.debug('apiRequest.request ==== ' + apiRequest.request);
            ApiCommonResponse apiResponse = ApiUtilities.doRequest(apiRequest);
            result = apiResponse.toString();
        } catch (Exception e) {
            Logger.error(e.getStackTraceString());
            Logger.error(e.getMessage());
            Logger.saveLog();
        }
        return result;
    }

    public class resultInitWrapper{
        @AuraEnabled public List<LegacySystem__c> legacySystemList{get;set;}
        @AuraEnabled public Map<String, List<interfaceOptions>> interfaceRouteMap{get;set;}
        @AuraEnabled public Map<String, String> exampleParamMap{get;set;}
        @AuraEnabled public String appName{get;set;}
    }

    public class interfaceOptions{
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String value{get;set;}

        public interfaceOptions(InterfaceRouteManager__c obj){
            this.label = obj.ServiceName__c + ' / ' + obj.InterfaceId__c;
            this.value = obj.ServiceName__c;
        }
    }
}